### PR TITLE
bg - Removed tabs in navbar that Riders should not be able to access

### LINKED ISSUE #7: BUG: Rider can see tabs in navbar they cant/shouldnt access
### Summary

A user with ONLY a rider role should not be able to see field relevant to other roles and only ride request should be available to them, but right now they can see a dropdown for `Shifts` and `Drivers Page`

### Expected Behavior

The user should only see the dropdown for `Ride Request`

### Current / Observed Behavior

image

### Steps to Reproduce

1. Log in as user with no roles
2. Get your role toggled by an admin to be a rider
3. View navbar

Implementation Todo:

- [ ] Edit `AppNavbar.js` and make sure that the tabs are not available to riders

### PR DESCRIPTION
**Pull request by bradygin**
This PR removes the `Shifts` and `Drivers Page` tabs in the navbar that were previously available for Riders to click on.

**Previous Behavior:**

Screenshot 2024-05-28 at 2 04 46 PM

**Current Behavior after this PR:**

Screenshot 2024-05-28 at 2 06 16 PM

**Dokku Deployment link**: https://gauchoride-qa.dokku-16.cs.ucsb.edu/

**Steps to Reproduce and Test:**

1. Log in as a user that only has Rider permissions. 
2. Check navbar and make sure only the Ride Request Tab shows. 

Fixes #7

### CODE REVIEW

**Review by KarstenLansing — DISMISSED** [review]
LGTM

**Review by spark686 — DISMISSED** [review]
LGTM

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 1]
```diff
@@ -90,14 +90,14 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
                 )
               }
               {
-                !hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
+                !hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && !hasRole(currentUser, "ROLE_RIDER") && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js]: Wouldn't it be easier to say: 

```suggestion
                hasRole(currentUser, "ROLE_ADMIN") (
```

That would be a lot more clear.  Is there a case where that's the wrong logic?   What you have here seems needlessly complex, and it would also prevent Admins that are also drivers or riders from accessing the menu which I don't think we want to do.

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 2]
```diff
@@ -90,14 +90,14 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
...
                   <NavDropdown title="Shifts" id="appnavbar-shift-dropdown" data-testid="appnavbar-shift-dropdown" >
                     <NavDropdown.Item data-testid="appnavbar-shift-dropdown-shifts" as={Link} to="/shift/">Shifts</NavDropdown.Item>
                   </NavDropdown>
                 )
               }
               {
-                hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
+                hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && !hasRole(currentUser, "ROLE_RIDER") && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js]:
```suggestion
                hasRole(currentUser, "ROLE_ADMIN") || hasRole(currentUser, "ROLE_DRIVER") 
```

**Review by pconrad — CHANGES_REQUESTED** [review]
I think we can simplify this logic a lot

**Review by pconrad — APPROVED** [review]
LGTM
